In [ ]:
tablero = [[0,2,3,0],[3,4,1,0],[2,0,0,3],[0,0,2,0]]
tab = [[9,3,4,2,1,8,6,7,5],[1,7,2,5,6,9,4,8,3],[5,8,6,3,7,4,2,9,1],[3,2,8,9,4,5,7,1,6],[6,9,5,7,3,1,8,4,2],[4,1,7,8,2,6,3,5,9],[8,4,1,6,9,2,5,3,7],[2,5,3,1,8,7,9,6,4],[7,6,9,4,5,3,1,2,8]]

In [ ]:
import math
def imprime_tablero(tablero):
  n = int(math.sqrt(len(tablero)))
  tam = len(tablero)
  for i in range(tam):
    print('|', end='')
    for j in range(tam):
      if tablero[i][j] == 0:
        print(" ", end='')
      else:
        print(tablero[i][j], end='')
      if (j+1) % n == 0:
        print("|", end='')
    print()
    if (i+1) %n == 0:
      print('-'*tam*2)

In [ ]:
imprime_tablero(tablero)

| 2|3 |
|34|1 |
--------
|2 | 3|
|  |2 |
--------


In [ ]:
def get_posiciones_de_cambio(tablero):
  pos_cambio = []
  for i in range(len(tablero)):
    for j in range(len(tablero)):
      if tablero[i][j] == 0:
        pos_cambio.append((i,j))
  return pos_cambio

In [ ]:
get_posiciones_de_cambio(tablero)

[(0, 0), (0, 3), (1, 3), (2, 1), (2, 2), (3, 0), (3, 1), (3, 3)]

In [ ]:
import copy
def genera_soluciones(tablero, pos_cambio):
  posibilidades = []
  for cambio in pos_cambio:
    #Tomar las posiciones
    i, j = cambio[0], cambio[1]
    if tablero[i][j] < len(tablero):
      nuevo_tablero = copy.deepcopy(tablero)
      nuevo_tablero[i][j] += 1
      posibilidades.append(nuevo_tablero)
  return posibilidades

In [ ]:
posiciones = get_posiciones_de_cambio(tablero)
genera_soluciones(tablero, posiciones)

[[[1, 2, 3, 0], [3, 4, 1, 0], [2, 0, 0, 3], [0, 0, 2, 0]],
 [[0, 2, 3, 1], [3, 4, 1, 0], [2, 0, 0, 3], [0, 0, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 1], [2, 0, 0, 3], [0, 0, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 0], [2, 1, 0, 3], [0, 0, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 0], [2, 0, 1, 3], [0, 0, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 0], [2, 0, 0, 3], [1, 0, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 0], [2, 0, 0, 3], [0, 1, 2, 0]],
 [[0, 2, 3, 0], [3, 4, 1, 0], [2, 0, 0, 3], [0, 0, 2, 1]]]

In [ ]:
def colisiones_lista(tablero):
  colisiones = 0
  for l in tablero:
    colisiones += sum(l.count(e) for e in l) - len(l)
  return colisiones

In [ ]:
colisiones_lista(tablero)

10

In [ ]:
import numpy as np
def genera_celdas(tablero):
  n = int(math.sqrt(len(tablero)))
  tab = np.array(tablero)
  res = []
  for i in range(n):
    cuadros = tab[(i*n) : (i*n)+n]
    for j in range(n):
      cuadro = cuadros[:, (j*n) : (j*n) + n]
      cuadro = cuadro.flatten()
      res.append(cuadro.tolist())
  return res

In [ ]:
print(tablero)
genera_celdas(tablero)

[[0, 2, 3, 0], [3, 4, 1, 0], [2, 0, 0, 3], [0, 0, 2, 0]]


[[0, 2, 3, 4], [3, 0, 1, 0], [2, 0, 0, 0], [0, 3, 2, 0]]

In [ ]:
def checar_colisiones(tablero):
  colisiones = 0
  #Colisiones horizontales
  colisiones += colisiones_lista(tablero)
  #Colisiones verticales
  aux = np.array(tablero).transpose().tolist()
  colisiones += colisiones_lista(aux)
  #Colisiones en celdas
  aux2 = genera_celdas(tablero)
  colisiones += colisiones_lista(aux2)
  return colisiones

In [ ]:
checar_colisiones([[4,1,3,2],[2,3,4,1],[3,2,1,4],[1,4,2,3]])

0

In [ ]:
def checar_ceros(tablero):
  ceros = 0
  for l in tablero:
    ceros += l.count(0)
  return ceros

In [ ]:
checar_ceros(tablero)

8

In [ ]:
def goal_test(tablero):
  if checar_colisiones(tablero) == 0 and checar_ceros(tablero) == 0:
    return True
  return False

In [ ]:
goal_test([[4,1,3,2],[2,3,4,1],[3,2,1,4],[1,4,2,3]])

True

In [ ]:
#Para crear el fenotipo a partir del genotipo, es necesario transformar la representación del AG a la
# estructura de una solución o un tablero
def individuo_to_solucion(tablero, individuo, posiciones):
  #Se genera una copia completa del tablero
  tab_aux = copy.deepcopy(tablero)
  for i in range(len(posiciones)):
    x, y = posiciones[i][0], posiciones[i][1]
    tab_aux[x][y] = individuo[i]
  return tab_aux

In [ ]:
tablero = [[0,2,4,0],[4,3,0,0],[3,4,1,2],[2,0,3,4]]
n = len(tablero)
pos = get_posiciones_de_cambio(tablero)
print(pos)
gp = [i+1 for i in range(n)]
#Para generar un individuo, se necesita crear una lista con valores aleatorios del tamaño de las posiciones que se pueden cambiar
#Por ejemplo, si se cambian solo 5 posiciones del sudoku, un individuo (genotipo) tiene un máximo de 5 elementos
#Pues es una representación para que el algoritmo genético lo entienda
individuo = list(np.random.choice(gp, len(pos)))
print(individuo)
#sol_individuo = individuo_to_solucion(tablero, individuo, posiciones)
print("Tablero original")
imprime_tablero(tablero)
print("Tablero alterado")
#imprime_tablero(sol_individuo)

#Generar un conjunto de individuos que serán la población inicial para resolver el problema con el
# proceso de un AG
def generar_poblacion(tam_poblacion, genetic_pool, posiciones):
  poblacion = []
  for i in range(tam_poblacion):
    individuo = list(np.random.choice(genetic_pool, len(posiciones)))
    poblacion.append(individuo)
  return poblacion

[(0, 0), (0, 3), (1, 2), (1, 3), (3, 1)]
[3, 4, 3, 3, 3]
Tablero original
| 2|4 |
|43|  |
--------
|34|12|
|2 |34|
--------
Tablero alterado


In [ ]:
def encontro_solucion(poblacion, tablero, posiciones):
  for indviduo in poblacion:
    tab = individuo_to_solucion(tablero, individuo, posiciones)
    if checar_colisiones(tab) == 0:
      return individuo
  return None

In [ ]:
#Función que realiza un proceso de evaluación a cada uno de los individuos de una población
#En el caso de sudoku, se verifica las colisiones de cada individuo
def evaluacion_fitness(poblacion, tablero, posiciones, minimize= False):
  fitness_list = []
  for individuo in poblacion:
    tab = individuo_to_solucion(tablero, individuo, posiciones)
    colisiones = checar_colisiones(tab)
    fitness_list.append(colisiones)
  #En este punto se genera una lista donde cada elemento de ella, representa la cantidad de colisiones de cada solución
  print(fitness_list)
  print(sum(fitness_list))
  #El siguiente paso es generar un vector de probabilidades a partir de las colisiones para seleccionar los mejores
  #Se utiliza una estructura numpy para mejor procesamiento
  fitness_list = np.array(fitness_list)
  #El vector de probabilidad tiene que tener un valor entre 0 y 1 (Valor / total de la suma)
  fitness_list = fitness_list / fitness_list.sum()
  if minimize:
    #Dividir 1 sobre cada valor
    inverse = [1/x for x in fitness_list]
    #Dividir cada valor sobre el total
    inverse = [x / sum(inverse) for x in inverse]
    fitness_list = inverse
  return fitness_list

In [ ]:
#Función capaz de generar una nueva población de individuos a partir de los mejores individuos
# de la anterior generación
def nueva_generacion(poblacion, fitness, posiciones):
  tam_poblacion = len(poblacion)
  hijos = []
  for i in range(tam_poblacion // 2):
    #Tomar de manera aleatoria 2 padres, dada por un vector de probabilidad
    #Me da una lista con n numeros aleatorios entre un rango especifico dado un vector de probabilidad
    padres = np.random.choice(tam_poblacion, 2, p= fitness)
    #print(padres)
    punto_cruza = np.random.randint(len(posiciones))
    hijos += [poblacion[padres[0]][:punto_cruza] + poblacion[padres[1]][punto_cruza:]]
    hijos += [poblacion[padres[1]][:punto_cruza] + poblacion[padres[0]][punto_cruza:]]
  return hijos

In [ ]:
#Función que permite la mutación, que son pequeñas alteraciones
# en las características de los individuos
def mutar(individuos, prob, genetic_pool):
  individuos_mutados = []
  for i in range(len(individuos)):
    indv_mutado = individuos[i]
    for j in range(len(indv_mutado)):
      if np.random.random() < prob:
        mutacion = np.random.choice(genetic_pool)
        indv_mutado[j] = mutacion
    individuos_mutados.append(indv_mutado)
  return individuos_mutados

In [ ]:
def encontro_solucion(poblacion, tablero, posiciones):
  for p in poblacion:
    tab = individuo_to_solucion(tablero, p, posiciones)
    if checar_colisiones(tab) == 0:
      return p
  return None

In [ ]:
def resuelve_sudoku_ga(generaciones, prob_mutacion, tablero, poblacion_org, posiciones, genetic_pool):
  tam_poblacion = len(posiciones)
  poblacion = poblacion_org[:]
  for _ in range(generaciones):
    res = encontro_solucion(poblacion, tablero, posiciones)
    if res != None:
      print("Se encontro la solución: ", res)
      return res
    fitness_list = evaluacion_fitness(poblacion, tablero, posiciones, minimize= True)
    hijos = nueva_generacion(poblacion, fitness_list, posiciones)
    hijos_mutados = mutar(hijos, prob_mutacion, genetic_pool)
    poblacion = hijos_mutados
  return poblacion

In [ ]:
def juega_sudoku_ga(tablero, generaciones, tam_poblacion, prob_mutacion):
  n = len(tablero)
  posiciones = get_posiciones_de_cambio(tablero)
  genetic_pool = [i+1 for i in range(n)]
  poblacion = generar_poblacion(tam_poblacion, genetic_pool, posiciones)
  res = resuelve_sudoku_ga(generaciones, prob_mutacion, tablero, poblacion, posiciones, genetic_pool)
  return res

In [ ]:
tablero = [[0,2,4,0],[4,3,0,0],[3,4,1,2],[2,0,3,4]]
res = juega_sudoku_ga(tablero, 1000, 40, 0.005)

[12, 28, 14, 22, 22, 18, 30, 18, 22, 8, 16, 22, 12, 26, 28, 16, 26, 16, 20, 16, 22, 8, 6, 16, 18, 12, 20, 30, 20, 26, 24, 16, 16, 14, 20, 16, 18, 12, 14, 18]
738
[26, 16, 26, 16, 14, 8, 16, 20, 24, 8, 28, 28, 20, 16, 8, 16, 16, 22, 8, 6, 12, 14, 8, 14, 6, 12, 22, 14, 14, 20, 16, 26, 20, 12, 20, 12, 16, 18, 14, 22]
654
Se encontro la solución:  [1, 3, 2, 1, 1]


In [ ]:
tablero = [[0,2,4,0],[4,3,0,0],[3,4,1,2],[2,0,3,4]]
#meta = [[1, 2, 4, 3], [4, 3, 2, 1], [3, 4, 1, 2], [2, 1, 3, 4]]
imprime_tablero(tablero)
n = len(tablero)
posiciones = get_posiciones_de_cambio(tablero)
print(n)
print(posiciones)
#Piscina genética, son los posibles valores que puede adquirir una solución para
# el tablero de sudoku, en este caso solo puede tomar un máximo del 1-4 (para tableros de 4x4)
genetic_pool = [i+1 for i in range(n)]
print(genetic_pool)
poblacion = generar_poblacion(20, genetic_pool, posiciones)
print(poblacion[:10])
res = encontro_solucion(poblacion, tablero, posiciones)
if res != None:
  print("Se encontro una solución")
fitness_list = evaluacion_fitness(poblacion, tablero, posiciones)
print(fitness_list[:10])
fitness_list = evaluacion_fitness(poblacion, tablero, posiciones, minimize= True)
print(fitness_list[:10])
hijos = nueva_generacion(poblacion, fitness_list, posiciones)
print(hijos[:10])
fitness_hijos = evaluacion_fitness(hijos, tablero, posiciones, minimize= True)
print(fitness_hijos[:10])
hijos = mutar(hijos, 0.5, genetic_pool)
print(hijos[:10])
fitness_hijos = evaluacion_fitness(hijos, tablero, posiciones, minimize= True)
print(fitness_hijos[:10])

| 2|4 |
|43|  |
--------
|34|12|
|2 |34|
--------
4
[(0, 0), (0, 3), (1, 2), (1, 3), (3, 1)]
[1, 2, 3, 4]
[[3, 1, 1, 1, 3], [3, 4, 1, 3, 3], [4, 4, 1, 3, 1], [1, 1, 3, 2, 3], [1, 4, 2, 3, 4], [1, 2, 2, 2, 4], [2, 3, 3, 1, 1], [4, 3, 3, 3, 3], [4, 1, 2, 3, 2], [2, 1, 1, 4, 1]]
[22, 20, 18, 14, 14, 22, 12, 28, 14, 16, 26, 26, 14, 18, 28, 22, 16, 24, 20, 22]
396
[0.05555556 0.05050505 0.04545455 0.03535354 0.03535354 0.05555556
 0.03030303 0.07070707 0.03535354 0.04040404]
[22, 20, 18, 14, 14, 22, 12, 28, 14, 16, 26, 26, 14, 18, 28, 22, 16, 24, 20, 22]
396
[0.042204964623066894, 0.046425461085373584, 0.051583845650415086, 0.0663220872648194, 0.0663220872648194, 0.042204964623066894, 0.07737576847562264, 0.0331610436324097, 0.0663220872648194, 0.05803182635671697]
[[3, 4, 1, 3, 3], [3, 4, 2, 2, 4], [1, 1, 3, 4, 3], [1, 2, 4, 2, 3], [2, 3, 3, 4, 3], [1, 2, 4, 1, 1], [4, 1, 2, 3, 3], [3, 1, 1, 1, 2], [4, 1, 2, 3, 4], [1, 4, 2, 3, 2]]
[20, 22, 18, 22, 24, 10, 14, 22, 14, 14, 16, 18, 16, 20, 2

## Algoritmo PSO


In [ ]:
#Evalua una particula y retorna un valor
def funcion_objetivo(particula, tablero, posiciones):
  tab = individuo_to_solucion(tablero, particula, posiciones)
  return checar_colisiones(tab)

def obtener_mejor_global(enjambre, tablero, posiciones, mejor_global, mejor_valor):
  mejor = mejor_global
  mejor_val = mejor_valor
  for particula in enjambre:
    valor = funcion_objetivo(particula, tablero, posiciones)
    #Minimizar
    if valor < mejor_val:
       mejor = particula
       mejor_val = valor
  return mejor, mejor_val

#Función traduce un conjunto de valores decimales de un vector a los enteros más cercanos de otro vector
def mas_cercano(particula, limites):
  valores_cercanos = []
  for p in particula:
    valor_cercano = min(limites, key= lambda x: abs(x-p))
    valores_cercanos.append(valor_cercano)
  return valores_cercanos

In [ ]:
tablero = [[0,2,4,0],[4,3,0,0],[3,4,1,2],[2,0,3,4]]
n = len(tablero)
num_particulas = 30
iteraciones = 100
limit_pool = [i+1 for i in range(n)]
limites = (1, 4)
posiciones = get_posiciones_de_cambio(tablero)
dimensiones = len(posiciones)

w = 0.5 #Inercia
c1 = 1.5 #Coeficiente cognitivo
c2 = 1.5 #Coeficiente social

#Generación del enjambre de particulas
enjambre = np.array(generar_poblacion(num_particulas, limit_pool, posiciones)).astype('float64')
#Inicializar el vector de velocidades por cada particula
velocidades = np.random.uniform(-1, 1, (num_particulas, dimensiones))

print(enjambre[:10])
print(velocidades[:10])

mejores_posiciones_individuales = np.array(copy.deepcopy(enjambre)).astype('float64')
mejor_val = 10000
#Individuo de puros 0
mejor_global = [0] * len(posiciones)

print(mejores_posiciones_individuales[:10])
print(mejor_val)
print(mejor_global)

mejor_global, mejor_valor = obtener_mejor_global(enjambre, tablero, posiciones, mejor_global, mejor_val)

print(mejor_valor)
print(mejor_global)

for iteracion in range(iteraciones):
  for i in range(num_particulas):
    #Actualizar velocidades
    r1 = np.random.random(dimensiones)
    r2 = np.random.random(dimensiones)
    velocidades[i] = (w * velocidades[i] +
                       r1 * c1 * (mejores_posiciones_individuales[i] - enjambre[i]) +
                       r2 * c2 * (mejor_global - enjambre[i]))

    #Actualizar posición
    enjambre[i] = enjambre[i] + velocidades[i]

    #Aplicar los límites de búsqueda
    enjambre[i] = np.clip(enjambre[i], limites[0], limites[1])

    particula_entero = mas_cercano(enjambre[i], limit_pool)
    valor = funcion_objetivo(particula_entero, tablero, posiciones)

    mejor_posicion_entero = mas_cercano(mejores_posiciones_individuales[i], limit_pool)
    if valor < funcion_objetivo(mejor_posicion_entero, tablero, posiciones):
      mejores_posiciones_individuales[i] = enjambre[i]

    #Actulizar la mejor posición global
    if valor < mejor_valor:
      mejor_valor = valor
      mejor_global = np.copy(enjambre[i])
  #Evaluar las nuevas posiciones
  #enjambre_entero = np.array([mas_cercano(particula, limit_pool) for particula in enjambre])
  #mejor_global, mejor_val = obtener_mejor_global(enjambre, tablero, posiciones, mejor_global, mejor_val)
  print("Iteración {}".format(iteracion))
  print(mejor_valor)
  print(mejor_global)

print("Finaliza la simulación")
mejor_entero = mas_cercano(mejor_global, limit_pool)
print("El mejor global es: {}".format(mejor_entero))
print("La cantidad de colisiones de ese tablero es: {}".format(mejor_valor))

tab = individuo_to_solucion(tablero, list(mejor_entero), posiciones)
imprime_tablero(tab)

[[4. 4. 3. 3. 1. 3. 4.]
 [1. 4. 4. 2. 1. 2. 2.]
 [3. 2. 2. 3. 1. 4. 1.]
 [3. 4. 3. 3. 4. 1. 2.]
 [4. 3. 1. 1. 4. 3. 1.]
 [1. 4. 4. 2. 4. 1. 1.]
 [1. 4. 1. 4. 2. 4. 2.]
 [4. 3. 3. 1. 3. 3. 2.]
 [1. 3. 4. 2. 4. 2. 4.]
 [4. 4. 1. 1. 3. 4. 3.]]
[[ 0.75262889 -0.90876231  0.83832188 -0.39762495  0.18707373  0.63049075
   0.28782427]
 [ 0.49634751  0.34909729 -0.55891582  0.03666075  0.53302968 -0.72893987
   0.20393311]
 [ 0.19800863 -0.03401284 -0.77876233  0.79349881 -0.19465004  0.98782869
   0.20464531]
 [-0.18029532  0.82331418 -0.35819428  0.21000462  0.88314668  0.74148775
  -0.90046566]
 [ 0.01871083 -0.92088895 -0.42635398  0.1289654   0.08047485  0.94114675
  -0.7671839 ]
 [ 0.1873533   0.0731351  -0.56128638 -0.89295393  0.14614323 -0.58576828
  -0.08278216]
 [ 0.84772844 -0.02809092  0.99356871  0.7075387   0.11641255 -0.87218593
  -0.98077644]
 [ 0.94535134 -0.02425558  0.65454627 -0.97510341 -0.19387379 -0.30132934
  -0.09337932]
 [ 0.15536121  0.13294209 -0.23393783 -0.568195

In [ ]:
l1 = np.array([3.6, 5.6, 3]).astype('float64')
l2 = np.array([3,4,5]).astype('float64')
mas_cercano(l1, l2)

[4.0, 5.0, 3.0]

In [ ]:
np.array(l) * 2

NameError: name 'l' is not defined